name: io_2014_contacts_demo
version: 0.0.2+1
author: Kevin Moore <kevmoo+github@google.com>
description: Dart, Polymer, Paper Sample App from Google IO 2014
homepage: https://github.com/kevmoo/io_2014_contacts_demo
environment:
 sdk: '>=1.7.0-dev.4.5 <2.0.0'
dependencies:
  paper_elements: '>=0.5.0 <0.6.0'
  polymer: '>=0.15.1 <0.16.0'
  redstone: any
  redstone_mapper: any
  redstone_mapper_mongo: any
  shelf_static: any
  grinder: any
transformers:
- redstone_mapper
- polymer:
    entry_points:
    - web/index.html
