name: io_2014_contacts_demo
version: 0.0.2+1
author: Kevin Moore <kevmoo+github@google.com>
description: Dart, Polymer, Paper Sample App from Google IO 2014
homepage: https://github.com/kevmoo/io_2014_contacts_demo
environment:
  sdk: '>=1.7.0-dev.4.5 <2.0.0'
dependencies:
  redstone: '>=0.5.17 <0.6.0'
  redstone_mapper: '>=0.1.9 <0.2.0'
  redstone_mapper_mongo: '0.1.1+1 <0.2.0'
  shelf_static: '>=0.2.0 <0.3.0'
  shelf_proxy: '>=0.1.0+1 <0.2.0'
  core_elements: '>=0.3.1+1 <0.4.0'
  paper_elements: '>=0.4.1 <0.5.0'
  polymer: '>=0.15.0 <0.16.0'
  grinder: '>=0.6.1 <0.7.0'
transformers:
- redstone_mapper
- polymer:
    entry_points:
      - web/index.html
