name: 'io_2016_contacts_demo'
version: 0.0.1
description: A web app built using polymer.dart.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  analyzer: "0.27.1"
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.8
  polymer: ^1.0.0-rc.15
  web_components: ^0.12.0
  redstone:
    git: https://github.com/redstone-dart/redstone.git
  redstone_mapper:
    git: https://github.com/redstone-dart/redstone_mapper.git
  redstone_mapper_mongo:
    git: https://github.com/redstone-dart/redstone_mapper_mongo.git
  jsproxyize:
    git: https://github.com/llamadonica/jsproxyize.git
  shelf_static: any
  grinder: any
  observe: any
  json_stream_parser:
    git: https://github.com/llamadonica/dart-json-stream-parser.git
  uuid: any

transformers:
- jsproxyize
- polymer:
    entry_points: web/index.html
- redstone_mapper:
    $include: web/main.dart
- $dart2js:
    minify: false
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
